import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiDelete, apiGet, apiPost, apiPut } from '../../lib/apiClient';
import type { AlertRuleDto, CreateWatchlistItemRequestDto, CreateWatchlistRequestDto, GenerateWatchlistFromRuleResponseDto, SaveWatchlistGenerationRuleRequestDto, UpdateAlertRuleRequestDto, UpdateWatchlistGenerationRuleRequestDto, UpdateWatchlistItemRequestDto, UpdateWatchlistRequestDto, WatchlistDefinitionDto, WatchlistDetailDto, WatchlistGenerationRuleDto, WatchlistItemDto } from '../../types/watchlist.types';

export function useWatchlistsQuery(userId: string) { return useQuery({ queryKey: ['watchlists', userId], queryFn: () => apiGet<WatchlistDefinitionDto[]>('/api/watchlists', { userId }), enabled: !!userId }); }
export function useCreateWatchlistMutation(userId: string) { const qc=useQueryClient(); return useMutation({ mutationFn:(body:CreateWatchlistRequestDto)=>apiPost<WatchlistDefinitionDto>('/api/watchlists', body), onSuccess:()=>qc.invalidateQueries({queryKey:['watchlists', userId]}) }); }
export function useUpdateWatchlistMutation(userId: string) { const qc=useQueryClient(); return useMutation({ mutationFn:(body:UpdateWatchlistRequestDto)=>apiPut<WatchlistDefinitionDto>(`/api/watchlists/${body.watchlistId}`, body), onSuccess:(_d,v)=>{qc.invalidateQueries({queryKey:['watchlists', userId]}); qc.invalidateQueries({queryKey:['watchlist-detail', userId, v.watchlistId]});} }); }
export function useDeleteWatchlistMutation(userId: string) { const qc=useQueryClient(); return useMutation({ mutationFn:(watchlistId:string)=>apiDelete<{deleted:boolean}>(`/api/watchlists/${watchlistId}`, { userId }), onSuccess:()=>qc.invalidateQueries({queryKey:['watchlists', userId]}) }); }
export function useWatchlistDetailQuery(userId: string, watchlistId?: string | null) { return useQuery({ queryKey:['watchlist-detail', userId, watchlistId], queryFn:()=>apiGet<WatchlistDetailDto>(`/api/watchlists/${watchlistId}`, { userId }), enabled: !!userId && !!watchlistId }); }
export function useWatchlistItemsQuery(userId: string, watchlistId?: string | null) { return useQuery({ queryKey: ['watchlist-items', userId, watchlistId], queryFn: () => apiGet<WatchlistItemDto[]>(`/api/watchlists/${watchlistId}/items`, { userId }), enabled: !!userId && !!watchlistId }); }
export function useAddWatchlistItemMutation(userId: string, watchlistId: string) { const qc=useQueryClient(); return useMutation({ mutationFn:(body:CreateWatchlistItemRequestDto)=>apiPost<WatchlistItemDto>(`/api/watchlists/${watchlistId}/items`, body), onSuccess:()=>{qc.invalidateQueries({queryKey:['watchlist-detail', userId, watchlistId]}); qc.invalidateQueries({queryKey:['watchlist-items', userId, watchlistId]});} }); }
export function useUpdateWatchlistItemMutation(userId: string, watchlistId: string) { const qc=useQueryClient(); return useMutation({ mutationFn:(body:UpdateWatchlistItemRequestDto)=>apiPut<WatchlistItemDto>(`/api/watchlists/${watchlistId}/items/${body.watchlistItemId}`, body), onSuccess:()=>{qc.invalidateQueries({queryKey:['watchlist-detail', userId, watchlistId]}); qc.invalidateQueries({queryKey:['watchlist-items', userId, watchlistId]});} }); }
export function useDeleteWatchlistItemMutation(userId: string, watchlistId: string) { const qc=useQueryClient(); return useMutation({ mutationFn:(watchlistItemId:string)=>apiDelete<{deleted:boolean}>(`/api/watchlists/${watchlistId}/items/${watchlistItemId}`, { userId }), onSuccess:()=>{qc.invalidateQueries({queryKey:['watchlist-detail', userId, watchlistId]}); qc.invalidateQueries({queryKey:['watchlist-items', userId, watchlistId]});} }); }
export function useWatchlistRulesQuery(userId: string) { return useQuery({ queryKey: ['watchlist-rules', userId], queryFn: () => apiGet<WatchlistGenerationRuleDto[]>('/api/watchlists/rules', { userId }), enabled: !!userId }); }
export function useSaveWatchlistRuleMutation(userId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (body: SaveWatchlistGenerationRuleRequestDto) => apiPost<WatchlistGenerationRuleDto>('/api/watchlists/rules', body), onSuccess: () => qc.invalidateQueries({ queryKey: ['watchlist-rules', userId] }) }); }
export function useUpdateWatchlistRuleMutation(userId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (body: UpdateWatchlistGenerationRuleRequestDto) => apiPut<WatchlistGenerationRuleDto>(`/api/watchlists/rules/${body.ruleId}`, body), onSuccess: () => qc.invalidateQueries({ queryKey: ['watchlist-rules', userId] }) }); }
export function useDeleteWatchlistRuleMutation(userId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (ruleId: string) => apiDelete<{deleted:boolean}>(`/api/watchlists/rules/${ruleId}`, { userId }), onSuccess: () => qc.invalidateQueries({ queryKey: ['watchlist-rules', userId] }) }); }
export function useGenerateWatchlistRuleMutation(userId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (ruleId: string) => apiPost<GenerateWatchlistFromRuleResponseDto>(`/api/watchlists/rules/${ruleId}/generate?userId=${encodeURIComponent(userId)}`, {}), onSuccess: () => { qc.invalidateQueries({ queryKey: ['watchlist-rules', userId] }); qc.invalidateQueries({ queryKey: ['watchlists', userId] }); } }); }
export function useAlertRulesQuery(userId: string) { return useQuery({ queryKey: ['alert-rules', userId], queryFn: () => apiGet<AlertRuleDto[]>('/api/alerts/rules', { userId }), enabled: !!userId }); }
export function useAlertRuleDetailQuery(userId: string, alertRuleId?: string | null) { return useQuery({ queryKey:['alert-rule-detail', userId, alertRuleId], queryFn:()=>apiGet<AlertRuleDto>(`/api/alerts/rules/${alertRuleId}`, { userId }), enabled: !!userId && !!alertRuleId }); }
export function useUpdateAlertRuleMutation(userId: string) { const qc=useQueryClient(); return useMutation({ mutationFn:(body:UpdateAlertRuleRequestDto)=>apiPut<AlertRuleDto>(`/api/alerts/rules/${body.alertRuleId}`, body), onSuccess:(_d,v)=>{qc.invalidateQueries({queryKey:['alert-rules', userId]}); qc.invalidateQueries({queryKey:['alert-rule-detail', userId, v.alertRuleId]});} }); }
export function useDeleteAlertRuleMutation(userId: string) { const qc=useQueryClient(); return useMutation({ mutationFn:(alertRuleId:string)=>apiDelete<{deleted:boolean}>(`/api/alerts/rules/${alertRuleId}`, { userId }), onSuccess:()=>qc.invalidateQueries({queryKey:['alert-rules', userId]}) }); }
export function useUpdateAlertStatusMutation(userId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ alertRuleId, status }: { alertRuleId: string; status: string }) => apiPut<{updated:boolean}>(`/api/alerts/rules/${alertRuleId}/status?userId=${encodeURIComponent(userId)}&status=${encodeURIComponent(status)}`, {}), onSuccess: (_d,v) => { qc.invalidateQueries({ queryKey: ['alert-rules', userId] }); qc.invalidateQueries({queryKey:['alert-rule-detail', userId, v.alertRuleId]}); } }); }
