import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiDelete, apiGet, apiPost, apiPut } from '../../lib/apiClient';
import type { SaveWorkspaceLayoutPresetRequestDto, UpdateWorkspaceLayoutPresetRequestDto, WorkspaceLayoutPreset, WorkspaceLayoutPresetShareDto } from '../../types/workspace.types';

export function useWorkspaceLayoutPresetsQuery(userId: string) { return useQuery({ queryKey: ['workspace-layout-presets', userId], queryFn: () => apiGet<WorkspaceLayoutPreset[]>('/api/workspace/layout-presets', { userId }), enabled: !!userId }); }
export function useSharedWorkspaceLayoutPresetsQuery(userId: string) { return useQuery({ queryKey: ['workspace-shared-layout-presets', userId], queryFn: () => apiGet<WorkspaceLayoutPreset[]>('/api/workspace/shared-layout-presets', { userId }), enabled: !!userId }); }
export function useSaveWorkspaceLayoutPresetMutation() { const qc = useQueryClient(); return useMutation({ mutationFn: (body: SaveWorkspaceLayoutPresetRequestDto) => apiPost<WorkspaceLayoutPreset>('/api/workspace/layout-presets', body), onSuccess: (_d, vars) => qc.invalidateQueries({ queryKey: ['workspace-layout-presets', vars.userId] }) }); }
export function useUpdateWorkspaceLayoutPresetMutation() { const qc = useQueryClient(); return useMutation({ mutationFn: (body: UpdateWorkspaceLayoutPresetRequestDto) => apiPut<WorkspaceLayoutPreset>(`/api/workspace/layout-presets/${body.presetId}`, body), onSuccess: (_d, vars) => qc.invalidateQueries({ queryKey: ['workspace-layout-presets', vars.userId] }) }); }
export function useMarkDefaultWorkspaceLayoutPresetMutation(userId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (presetId: string) => apiPost<WorkspaceLayoutPreset>(`/api/workspace/layout-presets/${presetId}/default?userId=${encodeURIComponent(userId)}`, {}), onSuccess: () => qc.invalidateQueries({ queryKey: ['workspace-layout-presets', userId] }) }); }
export function useMarkFavoriteWorkspaceLayoutPresetMutation(userId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: ({ presetId, favorite }: { presetId: string; favorite: boolean }) => apiPost<WorkspaceLayoutPreset>(`/api/workspace/layout-presets/${presetId}/favorite?userId=${encodeURIComponent(userId)}&favorite=${favorite}`, {}), onSuccess: () => qc.invalidateQueries({ queryKey: ['workspace-layout-presets', userId] }) }); }
export function useDeleteWorkspaceLayoutPresetMutation(userId: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (presetId: string) => apiDelete<{ deleted: boolean }>('/api/workspace/layout-presets/' + presetId, { userId }), onSuccess: () => qc.invalidateQueries({ queryKey: ['workspace-layout-presets', userId] }) }); }
export function useWorkspaceLayoutPresetSharesQuery(presetId?: string | null, ownerUserId?: string | null) { return useQuery({ queryKey:['workspace-layout-preset-shares', presetId, ownerUserId], queryFn:()=>apiGet<WorkspaceLayoutPresetShareDto[]>(`/api/workspace/layout-presets/${presetId}/shares`, { ownerUserId: ownerUserId ?? '' }), enabled: !!presetId && !!ownerUserId }); }
export function useSaveWorkspaceLayoutPresetShareMutation(presetId: string, ownerUserId: string) { const qc=useQueryClient(); return useMutation({ mutationFn:(body:{ sharedWithUserId:string; permission:'VIEW'|'EDIT'; })=>apiPost<WorkspaceLayoutPresetShareDto>(`/api/workspace/layout-presets/${presetId}/shares`, { presetId, ownerUserId, ...body }), onSuccess:()=>qc.invalidateQueries({queryKey:['workspace-layout-preset-shares', presetId, ownerUserId]}) }); }
export function useUpdateWorkspaceLayoutPresetSharePermissionMutation(presetId: string, ownerUserId: string) { const qc=useQueryClient(); return useMutation({ mutationFn:(body:{ sharedWithUserId:string; permission:'VIEW'|'EDIT'; })=>apiPut<WorkspaceLayoutPresetShareDto>(`/api/workspace/layout-presets/${presetId}/shares`, { presetId, ownerUserId, ...body }), onSuccess:()=>qc.invalidateQueries({queryKey:['workspace-layout-preset-shares', presetId, ownerUserId]}) }); }
export function useDeleteWorkspaceLayoutPresetShareMutation(presetId: string, ownerUserId: string) { const qc=useQueryClient(); return useMutation({ mutationFn:(sharedWithUserId:string)=>apiDelete<{deleted:boolean}>(`/api/workspace/layout-presets/${presetId}/shares`, { ownerUserId, sharedWithUserId }), onSuccess:()=>qc.invalidateQueries({queryKey:['workspace-layout-preset-shares', presetId, ownerUserId]}) }); }
